# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Iñigo Imaz"
baseurl: ""
description: >- # this means to ignore newlines until "baseurl:"
twitter_username: username
github_username: inimaz
minimal_mistakes_skin: contrast
search: true
masthead_title: " "

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme:  "mmistakes/minimal-mistakes"

og_image: /assets/images/bio-photo.jpg
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-picture-tag
  - jekyll-include-cache

author:
  name   : "Iñigo Imaz"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software development + Data Science"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/inimaz"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/inigo-imaz-chacon/"
      

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/inimaz"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/inigo-imaz-chacon/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
      toc: true
      toc_label: "Table of Content"
      toc_icon: "map-signs"
  # _academic-publications
  - scope:
      path: ""
      type: academic-publications
    values:
      layout: single
      author_profile: true
      share: true
      toc: true
      toc_label: "Table of Content"
      toc_icon: "atom"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  academic-publications:
    output: true
    permalink: /:collection/:path/